name: Deploy Codelabs HTML to GitHub Pages

on:
  push:
    branches:
      - gh-pages
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.19.1'
      - run: go install github.com/googlecodelabs/tools/claat@latest
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: ./codelabs/tooling/codelab.py all
      - run: git status
      - run: ls
      - run: cd codelabs && ls
      - run: cd codelabs && cd html && ls
      # - name: Upload Artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     path: "codelabs/html/"
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated changes
          branch: gh-pages
          commit_options: '--no-verify --signoff'
          file_pattern: 'codelabs/html/appyx-hello-world codelabs/html/appyx-navigation codelabs/html/appyx-custom-animation'

      # - run: |
      #     git checkout gh-pages
      #     git add -f codelabs/html
      #     git commit -m "update codelabs"
      #     git push

  # deploy:
  #   name: Deploy
  #   runs-on: ubuntu-latest
  #   needs: build
  #   permissions:
  #     pages: write
  #     id-token: write
  #   steps:
      
