name: Deploy Codelabs HTML to GitHub Pages

on:
  push:
    branches:
      - code-labs-markdown
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.19.1'
      - run: go install github.com/googlecodelabs/tools/claat@latest
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: ./codelabs/tooling/codelab.py all
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          path: "codelabs/html/"
      - run: pip install mkdocs-material
      - run: mkdocs build --strict

  # deploy:
  #   name: Deploy
  #   runs-on: ubuntu-latest
  #   needs: build
  #   permissions:
  #     pages: write
  #     id-token: write
  #   steps:
      
