name: Deploy mkdocs to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.19.1'
      - run: go install github.com/googlecodelabs/tools/claat@latest
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: ./codelab/tooling/codelab.py all 
  # deploy:
  #   name: Deploy
  #   needs: build
  #   permissions:
  #     pages: write
  #     id-token: write

  #   environment:
  #     name: github-pages
  #     url: ${{ steps.deployment.outputs.page_url }}

  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Deploy to GitHub Pages
  #       id: deployment
  #       uses: actions/deploy-pages@v1